name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure RDP
        shell: powershell
        run: |
          $rdpPath = 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
          Set-ItemProperty -Path $rdpPath -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
