name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0

      - name: Create RDP User
        run: |
          net user Skyro hUP^1@H=m2:q6Qa4 /add
          net localgroup administrators Skyro /add

      - name: Baixar LocalXpose
        run: |
          Invoke-WebRequest -Uri "https://bin.localxpose.io/arch/windows-amd64/localtun.exe" -OutFile "localtun.exe"

      - name: Iniciar Conexao TCP
        run: .\localtun.exe tunnel tcp --to localhost:3389

          
