name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure RDP
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0

      - name: Create RDP User
        shell: powershell
        run: |
          net user Skyro Senha123! /add /active:yes
          net localgroup administrators Skyro /add
          net accounts /maxpwage:UNLIMITED
          $Password = ConvertTo-SecureString "Senha123!" -AsPlainText -Force
          Set-LocalUser -Name "Skyro" -Password $Password

      - name: Install Tailscale
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi" -OutFile "tailscale-setup.msi"
          Start-Process msiexec.exe -Wait -ArgumentList '/i tailscale-setup.msi /quiet'

      - name: Connect Tailscale
        shell: powershell
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=gh-runner-$env:GITHUB_RUN_ID

      - name: Keep Alive
        shell: powershell
        run: |
          Write-Host "RDP is ready and running!"
          Start-Sleep -Seconds 3500
